package com.mahaesuvidha.chandrapanchangalarm
import android.Manifest;import android.content.pm.PackageManager;import android.os.Bundle;import androidx.activity.ComponentActivity;import androidx.activity.compose.setContent;import androidx.activity.result.contract.ActivityResultContracts;import androidx.compose.foundation.*;import androidx.compose.foundation.layout.*;import androidx.compose.foundation.shape.RoundedCornerShape;import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.*;import androidx.compose.ui.graphics.Color;import androidx.compose.ui.text.font.FontWeight;import androidx.compose.ui.unit.dp;import androidx.compose.ui.unit.sp;import androidx.core.content.ContextCompat;import com.google.android.gms.location.LocationServices;import com.mahaesuvidha.chandrapanchangalarm.alarm.AlarmScheduler;import com.mahaesuvidha.chandrapanchangalarm.model.*;import com.mahaesuvidha.chandrapanchangalarm.settings.AlarmPrefs;import kotlinx.coroutines.delay;import java.time.*;import java.time.format.DateTimeFormatter
class MainActivity:ComponentActivity(){private lateinit var scheduler:AlarmScheduler;private var locationText by mutableStateOf("स्थान शोधत आहे…");private val perm=registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){readLocation()};private val notif=registerForActivityResult(ActivityResultContracts.RequestPermission()){}
 override fun onCreate(b:Bundle?){super.onCreate(b);scheduler=AlarmScheduler(this);if(android.os.Build.VERSION.SDK_INT>=33)notif.launch(Manifest.permission.POST_NOTIFICATIONS);perm.launch(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION));readLocation();scheduler.scheduleAll();setContent{MaterialTheme{App(locationText,scheduler)}}}
 private fun readLocation(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;LocationServices.getFusedLocationProviderClient(this).lastLocation.addOnSuccessListener{l->if(l!=null)locationText="📍 ${"%.4f".format(l.latitude)}, ${"%.4f".format(l.longitude)} • LIVE" else locationText="📍 स्थान उपलब्ध नाही"}}
}
@Composable private fun App(location:String,scheduler:AlarmScheduler){var moon by remember{mutableStateOf(AstroCalculator.moon())};var sun by remember{mutableStateOf(AstroCalculator.sun())};val prefs=remember{AlarmPrefs(androidx.compose.ui.platform.LocalContext.current)};var settings by remember{mutableStateOf(false)};LaunchedEffect(Unit){while(true){delay(30000);moon=AstroCalculator.moon();sun=AstroCalculator.sun()}}
 val bg=Color(0xFF081522);Box(Modifier.fillMaxSize().background(bg)){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(12.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("🌙 चंद्र सूर्य अलार्म",color=Color.White,fontSize=25.sp,fontWeight=FontWeight.Bold);Text("LIVE • AUTO ALARM",color=Color.LightGray)};Text("⚙️",fontSize=30.sp,modifier=Modifier.clickable{settings=true})};Spacer(Modifier.height(8.dp));Text(location,color=Color(0xFF39D353));Spacer(Modifier.height(12.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){BodyCard(Modifier.weight(1f),moon,Color(0xFF102B40),Color(0xFF72B7FF));BodyCard(Modifier.weight(1f),sun,Color(0xFF332703),Color(0xFFFFC857))};Spacer(Modifier.height(16.dp));Text("🔔 अलार्म टेस्ट",color=Color.White,fontWeight=FontWeight.Bold,fontSize=20.sp);listOf("राशी","नक्षत्र","चरण").forEach{t->Spacer(Modifier.height(8.dp));Button(onClick={scheduler.scheduleTest(t)},modifier=Modifier.fillMaxWidth()){Text("$t बदल Test Alarm (10 सेकंद)")}};Spacer(Modifier.height(20.dp));Text("टीप: सध्याचा calculation engine approximation आहे; पंचांगाशी production validation केल्यानंतरच याला अंतिम अचूकता द्यावी.",color=Color.LightGray,fontSize=12.sp)}
 if(settings)SettingsDialog(prefs,{scheduler.scheduleAll()},{settings=false})}}
@Composable private fun BodyCard(mod:Modifier,s:AstroState,card:Color,accent:Color){Card(mod,colors=CardDefaults.cardColors(containerColor=card),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(10.dp)){Text(if(s.body=="चंद्र")"🌙 चंद्र" else "☀️ सूर्य",color=Color.White,fontWeight=FontWeight.Bold,fontSize=20.sp);Text("● LIVE",color=Color(0xFF39D353),fontSize=11.sp);RowLine("राशी",s.rashi.marathi);RowLine("नक्षत्र",s.nakshatra.marathi);RowLine("चरण",s.pada.toString());Divider(Modifier.padding(vertical=6.dp));Text("पुढील बदल",color=accent,fontWeight=FontWeight.Bold);Change(s.nextRashi, s.nextRashiMillis,accent);Change(s.nextNakshatra,s.nextNakshatraMillis,accent);Change(s.nextCharan,s.nextCharanMillis,accent)}}
@Composable private fun RowLine(a:String,b:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(a,color=Color.LightGray,fontSize=12.sp);Text(b,color=Color.White,fontSize=13.sp,fontWeight=FontWeight.Bold)}}
@Composable private fun Change(v:String,t:Long,c:Color){val f=DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");Text(v,color=Color.White,fontSize=12.sp);Text(Instant.ofEpochMilli(t).atZone(ZoneId.of("Asia/Kolkata")).format(f),color=c,fontSize=11.sp);Spacer(Modifier.height(5.dp))}
@Composable private fun SettingsDialog(p:AlarmPrefs,reschedule:()->Unit,close:()->Unit){var moon by remember{mutableStateOf(p.moon)};var sun by remember{mutableStateOf(p.sun)};var r by remember{mutableStateOf(p.rashi)};var n by remember{mutableStateOf(p.nak)};var pa by remember{mutableStateOf(p.pada)};AlertDialog(onDismissRequest=close,title={Text("⚙️ अलार्म सेटिंग्स")},text={Column{Toggle("🌙 चंद्र अलार्म",moon){moon=it};Toggle("☀️ सूर्य अलार्म",sun){sun=it};Toggle("राशी बदल",r){r=it};Toggle("नक्षत्र बदल",n){n=it};Toggle("चरण बदल",pa){pa=it}}},confirmButton={Button(onClick={p.moon=moon;p.sun=sun;p.rashi=r;p.nak=n;p.pada=pa;reschedule();close()}){Text("Save")}},dismissButton={TextButton(onClick=close){Text("Cancel")}})}
@Composable private fun Toggle(t:String,v:Boolean,set:(Boolean)->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(t,Modifier.weight(1f));Switch(v,set)}}
